#37 Simultaneous safe reconstruction fix
safient/safient-core-js pull request #38
Opened 2022-01-07 11:17 UTC by yathishram

## Description:

This PR allows for multiple guardians to simultaneously update the safe stage and recover the safe.

## Added:

List the added features
* `updateDecShard` - To update the shards on the guardian's user profiles
*  `getDecShards` - To fetch the `decShards` for a safe

## Modified:

List the modified features
* Adds a `decShard` key to `SafeMeta` in the `User` field to allow for concurrent writes to DB
* Feature 2

## Todo:

List the TODO features
[] Add `Guardian` boolean value on user profiles

2022-01-10 11:15 UTC, koshikraj requested changes

2022-01-10 11:15 UTC, koshikraj commented on src/utils/ceramicBootstrap.js
> +  const ceramic = new Ceramic(CERAMIC_URL)
We need to add the Ceramic UR in `network.json` and use based in the selected network.
test: `https://ceramic-clay.safient.io`
mainnet: test: `https://ceramic.safient.io`
local and dev: test: `http://0.0.0.0:7007`

2022-01-10 14:09 UTC, yathishram commented
> Do we have to manually update this every time we deploy locally?

It's a one-time thing. Like contract addresses. So I guess it's fine for now.

2022-01-11 06:14 UTC, koshikraj approved these changes

2022-01-11 06:15 UTC, merged