This PR contains API updates and fixes
safient/safient-core-js pull request #8
Opened 2021-08-12 11:27 UTC by yathishram

2021-08-31 10:16 UTC, koshikraj commented on src/SafientCore.ts
> +        }else{
Add `else if` instead.

2021-08-31 10:16 UTC, koshikraj commented on src/types/types.ts
> +  claimType: number;
We should import the ClaimType from `@safient/claims` and use it here.

2021-08-31 13:15 UTC, yathishram commented on src/SafientCore.ts
> +const ClaimType = {
We can use that as well. I'll try doing that

2021-08-31 13:16 UTC, koshikraj commented on src/SafientCore.ts
> +const ClaimType = {
You need to update the `safient-contract-js` as well.

2021-09-02 05:09 UTC, koshikraj requested changes

2021-09-02 05:09 UTC, koshikraj commented on test/scenario4.js
> +      safeId = await creatorSc.safientCore.createNewSafe(creator.idx.id, beneficiary.idx.id, "Testing safe Data", true, 0, 6)
Pass the claim type instead of `int`. You can import from `@safient/claims`

2021-09-02 05:09 UTC, koshikraj commented on test/scenario4.js
> +      const result = await creatorSc.safientCore.sendSignal(safeId) //Passing a claim
This is actually failing the claim.

2021-09-02 05:09 UTC, koshikraj commented on test/scenario4.js
> +it('Should wait for somtime', async () => {
Don't make this is a separate test. You can add the delay in the previous test itself.

2021-09-02 05:09 UTC, koshikraj commented on package.json
>      "@magic-ext/oauth": "^0.7.0",
Update the package version  to `0.1.1-alpha`

2021-09-02 09:13 UTC, koshikraj approved these changes

2021-09-02 09:16 UTC, merged